AWSTemplateFormatVersion: '2010-09-09'
Description: Outputs the time
Resources:
  TimeFunction:
    Properties:
      Alarms:
      - Ref: AliasErrorMetricGreaterThanZeroAlarm
      - Ref: LatestVersionErrorMetricGreaterThanZeroAlarm
      AutoPublishAlias: live
      CodeUri: s3://api-gateway-demo-jkeating/428c2b4fa6d8d9d7fcc1535eab4f7a87
      DeploymentPreference: null
      Events:
        MyTimeApi:
          Properties:
            Method: GET
            Path: /TimeResource
          Type: Api
      Handler: index.handler
      Hooks:
        PostTraffic:
          Ref: PostTrafficLambdaFunction
        PreTraffic:
          Ref: PreTrafficLambdaFunction
      Runtime: nodejs6.10
      Type: Canary10Percent10Minutes
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
